// <auto-generated />
using CustomerMicroservice.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerMicroservice.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20221116152049_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CustomerMicroservice.Data.Entities.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CustomerModels");
                });

            modelBuilder.Entity("CustomerMicroservice.Data.Entities.CustomerModelSecurity", b =>
                {
                    b.Property<int>("ModelIdId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasIndex("ModelIdId");

                    b.ToTable("CustomerModelsSecurity");
                });

            modelBuilder.Entity("CustomerMicroservice.Data.Entities.CustomerModelSecurity", b =>
                {
                    b.HasOne("CustomerMicroservice.Data.Entities.CustomerModel", "ModelId")
                        .WithMany()
                        .HasForeignKey("ModelIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
